name: CI/CD - Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install --legacy-peer-deps


      # 4. Compiler le projet (Vite, React, etc.)
      - name: Build project
        run: npm run build

      # 5. Sauvegarder le dossier ./dist en tant qu’artefact
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build # Ce job attend que le job 'build' soit terminé

    steps:
      # 1. Télécharger les fichiers générés
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # 2. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
