name: CI - Build

on:
  push:
    branches:
      - dev  # Ceci va activer le workflow pour la branche dev

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 5. Builder le projet si tests OK
      - name: Build project
        run: npm run build

      # 6. Uploader les fichiers buildés
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build_and_test  # Ce job attend que le job 'build_and_test' soit terminé

    steps:
      # 1. Télécharger les fichiers générés
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # 2. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
